jobs:
  build_test:
    #docker:
    #  - image: docker/compose:1.25.3

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout

#      - run:
#          name: Running Unit Tests
#          command: |
#            echo "Running unit tests and building binary"
#            go mod download
#            make all
      - run:
          name: Build and Push Images
          command: |
            echo "Logging in to Docker Hub"
            docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
            sudo docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}

            echo "Setting Image Name"
            IMAGE_NAME="motivlabs/janus:$(date +%Y%m%d%H%M%S)-${CIRCLE_SHA1:0:6}"
            echo "Image Name"
            echo $IMAGE_NAME

            echo "Building Service Image"
            docker build -f ./Dockerfile --target=prod -t ${IMAGE_NAME} -t motivlabs/janus:latest .
            echo "Finished Building Service Image"

            echo "Pushing Service Images to Docker Hub"
            docker push $IMAGE_NAME
            echo "Pushed Extended Image Name"
            docker push motivlabs/janus:latest
            echo "Pushed Latest Image Name"

            COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo "got commit message: ${COMMIT_MESSAGE}"

            echo "Running Script to Update Impulse Docker-Compose with Correct Image"
            .circleci/update-impulse.sh "janus" ${IMAGE_NAME} ${GITHUB_OAUTH} "${COMMIT_MESSAGE}"
            echo "Impulse Updated"

workflows:
  version: 2
  build:
    jobs:
      - build_test:
          context: MotivLabs
          filters:
            branches:
              only:
                - master
